#include "idt.h" 
#include <stddef.h>
#include <io/serial.h>

static struct idt_entry_t idt[256];
static struct idtr_t idtr;

void exception_handler()
{
    __asm__ volatile ("cli; hlt");
}

void idt_load(void* idtr_address)
{
    // Use the "volatile" keyword to prevent compiler optimizations
    // Ensure the idtr_address is a pointer to the IDT structure
    __asm__ volatile ("lidt (%0)" : : "r" (idtr_address));
}

extern void isr0();
extern void isr1();
extern void isr2();
extern void isr3();
extern void isr4();
extern void isr5();
extern void isr6();
extern void isr7();
extern void isr8();
extern void isr9();
extern void isr10();
extern void isr11();
extern void isr12();
extern void isr13();
extern void isr14();
extern void isr15();
extern void isr16();
extern void isr17();
extern void isr18();
extern void isr19();
extern void isr20();
extern void isr21();
extern void isr22();
extern void isr23();
extern void isr24();
extern void isr25();
extern void isr26();
extern void isr27();
extern void isr28();
extern void isr29();
extern void isr30();
extern void isr31();
extern void isr32();
extern void isr33();
extern void isr34();
extern void isr35();
extern void isr36();
extern void isr37();
extern void isr38();
extern void isr39();
extern void isr40();
extern void isr41();
extern void isr42();
extern void isr43();
extern void isr44();
extern void isr45();
extern void isr46();
extern void isr47();
extern void isr48();
extern void isr49();
extern void isr50();
extern void isr51();
extern void isr52();
extern void isr53();
extern void isr54();
extern void isr55();
extern void isr56();
extern void isr57();
extern void isr58();
extern void isr59();
extern void isr60();
extern void isr61();
extern void isr62();
extern void isr63();
extern void isr64();
extern void isr65();
extern void isr66();
extern void isr67();
extern void isr68();
extern void isr69();
extern void isr70();
extern void isr71();
extern void isr72();
extern void isr73();
extern void isr74();
extern void isr75();
extern void isr76();
extern void isr77();
extern void isr78();
extern void isr79();
extern void isr80();
extern void isr81();
extern void isr82();
extern void isr83();
extern void isr84();
extern void isr85();
extern void isr86();
extern void isr87();
extern void isr88();
extern void isr89();
extern void isr90();
extern void isr91();
extern void isr92();
extern void isr93();
extern void isr94();
extern void isr95();
extern void isr96();
extern void isr97();
extern void isr98();
extern void isr99();
extern void isr100();
extern void isr101();
extern void isr102();
extern void isr103();
extern void isr104();
extern void isr105();
extern void isr106();
extern void isr107();
extern void isr108();
extern void isr109();
extern void isr110();
extern void isr111();
extern void isr112();
extern void isr113();
extern void isr114();
extern void isr115();
extern void isr116();
extern void isr117();
extern void isr118();
extern void isr119();
extern void isr120();
extern void isr121();
extern void isr122();
extern void isr123();
extern void isr124();
extern void isr125();
extern void isr126();
extern void isr127();
extern void isr128();
extern void isr129();
extern void isr130();
extern void isr131();
extern void isr132();
extern void isr133();
extern void isr134();
extern void isr135();
extern void isr136();
extern void isr137();
extern void isr138();
extern void isr139();
extern void isr140();
extern void isr141();
extern void isr142();
extern void isr143();
extern void isr144();
extern void isr145();
extern void isr146();
extern void isr147();
extern void isr148();
extern void isr149();
extern void isr150();
extern void isr151();
extern void isr152();
extern void isr153();
extern void isr154();
extern void isr155();
extern void isr156();
extern void isr157();
extern void isr158();
extern void isr159();
extern void isr160();
extern void isr161();
extern void isr162();
extern void isr163();
extern void isr164();
extern void isr165();
extern void isr166();
extern void isr167();
extern void isr168();
extern void isr169();
extern void isr170();
extern void isr171();
extern void isr172();
extern void isr173();
extern void isr174();
extern void isr175();
extern void isr176();
extern void isr177();
extern void isr178();
extern void isr179();
extern void isr180();
extern void isr181();
extern void isr182();
extern void isr183();
extern void isr184();
extern void isr185();
extern void isr186();
extern void isr187();
extern void isr188();
extern void isr189();
extern void isr190();
extern void isr191();
extern void isr192();
extern void isr193();
extern void isr194();
extern void isr195();
extern void isr196();
extern void isr197();
extern void isr198();
extern void isr199();
extern void isr200();
extern void isr201();
extern void isr202();
extern void isr203();
extern void isr204();
extern void isr205();
extern void isr206();
extern void isr207();
extern void isr208();
extern void isr209();
extern void isr210();
extern void isr211();
extern void isr212();
extern void isr213();
extern void isr214();
extern void isr215();
extern void isr216();
extern void isr217();
extern void isr218();
extern void isr219();
extern void isr220();
extern void isr221();
extern void isr222();
extern void isr223();
extern void isr224();
extern void isr225();
extern void isr226();
extern void isr227();
extern void isr228();
extern void isr229();
extern void isr230();
extern void isr231();
extern void isr232();
extern void isr233();
extern void isr234();
extern void isr235();
extern void isr236();
extern void isr237();
extern void isr238();
extern void isr239();
extern void isr240();
extern void isr241();
extern void isr242();
extern void isr243();
extern void isr244();
extern void isr245();
extern void isr246();
extern void isr247();
extern void isr248();
extern void isr249();
extern void isr250();
extern void isr251();
extern void isr252();
extern void isr253();
extern void isr254();
extern void isr255();

void idt_install()
{
    disable_interrupts();
    idtr.limit = (sizeof(struct idt_entry_t) * 256) - 1;
    idtr.base = (uint64_t)&idt;
    idt_load((void*)&idtr);

    idt_set_descriptor(0x00, isr0, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x01, isr1, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x02, isr2, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x03, isr3, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x04, isr4, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x05, isr5, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x06, isr6, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x07, isr7, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x08, isr8, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x09, isr9, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x0A, isr10, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x0B, isr11, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x0C, isr12, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x0D, isr13, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x0E, isr14, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x0F, isr15, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x10, isr16, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x11, isr17, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x12, isr18, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x13, isr19, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x14, isr20, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x15, isr21, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x16, isr22, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x17, isr23, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x18, isr24, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x19, isr25, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x1A, isr26, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x1B, isr27, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x1C, isr28, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x1D, isr29, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x1E, isr30, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x1F, isr31, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x20, isr32, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x21, isr33, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x22, isr34, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x23, isr35, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x24, isr36, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x25, isr37, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x26, isr38, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x27, isr39, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x28, isr40, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x29, isr41, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x2A, isr42, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x2B, isr43, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x2C, isr44, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x2D, isr45, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x2E, isr46, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x2F, isr47, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x30, isr48, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x31, isr49, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x32, isr50, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x33, isr51, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x34, isr52, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x35, isr53, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x36, isr54, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x37, isr55, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x38, isr56, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x39, isr57, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x3A, isr58, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x3B, isr59, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x3C, isr60, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x3D, isr61, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x3E, isr62, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x3F, isr63, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x40, isr64, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x41, isr65, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x42, isr66, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x43, isr67, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x44, isr68, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x45, isr69, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x46, isr70, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x47, isr71, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x48, isr72, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x49, isr73, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x4A, isr74, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x4B, isr75, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x4C, isr76, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x4D, isr77, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x4E, isr78, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x4F, isr79, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x50, isr80, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x51, isr81, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x52, isr82, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x53, isr83, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x54, isr84, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x55, isr85, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x56, isr86, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x57, isr87, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x58, isr88, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x59, isr89, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x5A, isr90, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x5B, isr91, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x5C, isr92, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x5D, isr93, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x5E, isr94, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x5F, isr95, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x60, isr96, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x61, isr97, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x62, isr98, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x63, isr99, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x64, isr100, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x65, isr101, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x66, isr102, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x67, isr103, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x68, isr104, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x69, isr105, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x6A, isr106, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x6B, isr107, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x6C, isr108, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x6D, isr109, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x6E, isr110, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x6F, isr111, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x70, isr112, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x71, isr113, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x72, isr114, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x73, isr115, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x74, isr116, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x75, isr117, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x76, isr118, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x77, isr119, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x78, isr120, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x79, isr121, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x7A, isr122, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x7B, isr123, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x7C, isr124, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x7D, isr125, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x7E, isr126, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x7F, isr127, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x80, isr128, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x81, isr129, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x82, isr130, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x83, isr131, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x84, isr132, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x85, isr133, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x86, isr134, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x87, isr135, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x88, isr136, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x89, isr137, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x8A, isr138, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x8B, isr139, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x8C, isr140, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x8D, isr141, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x8E, isr142, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x8F, isr143, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x90, isr144, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x91, isr145, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x92, isr146, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x93, isr147, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x94, isr148, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x95, isr149, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x96, isr150, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x97, isr151, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x98, isr152, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x99, isr153, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x9A, isr154, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x9B, isr155, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x9C, isr156, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x9D, isr157, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x9E, isr158, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0x9F, isr159, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xA0, isr160, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xA1, isr161, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xA2, isr162, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xA3, isr163, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xA4, isr164, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xA5, isr165, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xA6, isr166, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xA7, isr167, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xA8, isr168, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xA9, isr169, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xAA, isr170, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xAB, isr171, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xAC, isr172, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xAD, isr173, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xAE, isr174, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xAF, isr175, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xB0, isr176, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xB1, isr177, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xB2, isr178, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xB3, isr179, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xB4, isr180, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xB5, isr181, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xB6, isr182, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xB7, isr183, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xB8, isr184, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xB9, isr185, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xBA, isr186, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xBB, isr187, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xBC, isr188, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xBD, isr189, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xBE, isr190, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xBF, isr191, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xC0, isr192, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xC1, isr193, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xC2, isr194, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xC3, isr195, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xC4, isr196, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xC5, isr197, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xC6, isr198, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xC7, isr199, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xC8, isr200, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xC9, isr201, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xCA, isr202, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xCB, isr203, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xCC, isr204, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xCD, isr205, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xCE, isr206, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xCF, isr207, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xD0, isr208, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xD1, isr209, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xD2, isr210, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xD3, isr211, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xD4, isr212, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xD5, isr213, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xD6, isr214, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xD7, isr215, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xD8, isr216, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xD9, isr217, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xDA, isr218, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xDB, isr219, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xDC, isr220, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xDD, isr221, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xDE, isr222, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xDF, isr223, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xE0, isr224, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xE1, isr225, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xE2, isr226, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xE3, isr227, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xE4, isr228, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xE5, isr229, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xE6, isr230, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xE7, isr231, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xE8, isr232, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xE9, isr233, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xEA, isr234, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xEB, isr235, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xEC, isr236, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xED, isr237, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xEE, isr238, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xEF, isr239, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xF0, isr240, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xF1, isr241, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xF2, isr242, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xF3, isr243, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xF4, isr244, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xF5, isr245, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xF6, isr246, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xF7, isr247, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xF8, isr248, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xF9, isr249, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xFA, isr250, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xFB, isr251, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xFC, isr252, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xFD, isr253, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xFE, isr254, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);
    idt_set_descriptor(0xFF, isr255, IDT_FLAG_PRESENT | 0xE | IDT_FLAG_RING0);

    enable_interrupts();
    serial_printf("Enabled interrupts!\n");
}

void enable_interrupts()
{
    __asm__ volatile ("sti");
}

void disable_interrupts()
{
    __asm__ volatile ("cli");
}

uint16_t get_kernel_cs() {
    uint16_t cs_value;
    __asm__ volatile ("mov %%cs, %0" : "=rm" (cs_value));
    return cs_value;
}

void idt_set_descriptor(uint8_t vector, void* isr, uint8_t flags) {
    struct idt_entry_t* descriptor = &idt[vector];
 
    descriptor->isr_low        = (uint64_t)isr & 0xFFFF;
    descriptor->kernel_cs      = get_kernel_cs();
    descriptor->ist            = 0;
    descriptor->attributes     = flags;
    descriptor->isr_mid        = ((uint64_t)isr >> 16) & 0xFFFF;
    descriptor->isr_high       = ((uint64_t)isr >> 32) & 0xFFFFFFFF;
    descriptor->reserved       = 0;
}

void interrupt_manager(struct regs registers)
{
    
    serial_printf("Interrupt %d\n", registers.interrupt_num);

    serial_printf("RAX: %x RBX: %x RCX: %x RDX: %x\n", registers.rax, registers.rbx, registers.rcx, registers.rdx);

    return;
}